### ISSUE TITLE
Migration from 2.0

### ISSUE THREAD

**Issue by HavasiPeter** [Vaxza/Toyosatomimi-Files#1]
I have some problems when I update from 2.0. MySQL has error occured.

**Comment by Vaxza** [comment]
For current condition In 3.0 we don't release Migration setup now, Some tables has added for more feature. Easy way is Export your field and Import setup.sql again (3.0) to your MySQL.

**Comment by Vaxza** [comment]
**Issue has closed! If you have more questions, your can oepn it again and tag me.**

**Comment by Vaxza** [comment]
**Issue has closed! If you have more questions, your can oepn it again and tag me.**
